name: Terraform Plan and Upload

on:
  push:
    branches: [ main ]
  workflow_dispatch: {}

jobs:
  plan:
    runs-on: ubuntu-latest
    steps:
      - name: Checkout
        uses: actions/checkout@v4

      - name: Setup Terraform
        uses: hashicorp/setup-terraform@v2
        with:
          terraform_version: '1.5.7'

      - name: Terraform Init
        working-directory: envs/dev
        run: terraform init -input=false

      - name: Terraform Plan (binary)
        working-directory: envs/dev
        run: terraform plan -out=plan.tfplan -input=false

      - name: Save plan as text
        working-directory: envs/dev
        run: |
          terraform show -no-color plan.tfplan > plan.txt || true
          terraform show -json plan.tfplan > plan.json || true

      - name: Upload plan artifacts
        uses: actions/upload-artifact@v4
        with:
          name: terraform-plan
          path: |
            envs/dev/plan.tfplan
            envs/dev/plan.txt
            envs/dev/plan.json
